const ROOT_FOLDER_NAME = 'INSPECCIONES_INFRAESTRUCTURA';

function doGet(e) {
  const p = (e && e.parameter) || {};
  if (p.action === 'report') return HtmlService.createHtmlOutput(buildReportHtml_(p.anio || new Date().getFullYear(), p.mes || 'SIN_MES')).setTitle('Reporte mensual de inspección');
  if (p.action === 'generateReport') {
    try {
      const result = syncReport_({anio:p.anio, mes:p.mes, nombre:p.nombre || ('Reporte_' + p.anio + '_' + p.mes)});
      const prefix = String(p.prefix || '');
      if (prefix) return ContentService.createTextOutput(prefix + '(' + result.getContent() + ')').setMimeType(ContentService.MimeType.JAVASCRIPT);
      return result;
    } catch (err) {
      const obj = {ok:false,error:String(err && err.message ? err.message : err)};
      const prefix = String(p.prefix || '');
      if (prefix) return ContentService.createTextOutput(prefix + '(' + JSON.stringify(obj) + ')').setMimeType(ContentService.MimeType.JAVASCRIPT);
      return json_(obj);
    }
  }
  if (p.action === 'check') {
    const id = String(p.id || ''); const result = {ok:fileExistsInFolderTree_(getOrCreateFolder_(ROOT_FOLDER_NAME), id + '.json'),id:id};
    if (p.prefix) return ContentService.createTextOutput(String(p.prefix) + '(' + JSON.stringify(result) + ')').setMimeType(ContentService.MimeType.JAVASCRIPT);
    return json_(result);
  }
  return json_({ok:true,service:'INSPECCIONES_INFRAESTRUCTURA'});
}
function doPost(e){try{const data=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');if(data.action==='syncInspection')return syncInspection_(data);if(data.action==='syncReport')return syncReport_(data);throw new Error('Acción no válida.');}catch(err){return json_({ok:false,error:String(err&&err.message?err.message:err)})}}
function syncInspection_(data){if(!data.id)throw new Error('Falta el ID de inspección.');const root=getOrCreateFolder_(ROOT_FOLDER_NAME),year=String(data.anio||new Date(data.fecha||Date.now()).getFullYear()),month=safe_(data.mes||'SIN_MES'),day=Utilities.formatDate(new Date(data.fecha||Date.now()),Session.getScriptTimeZone(),'yyyy-MM-dd'),zone=safe_(data.zona||'SIN_ZONA'),point=safe_(data.punto||'SIN_PUNTO'),yearFolder=getOrCreateFolder_(year,root),monthFolder=getOrCreateFolder_(month,yearFolder),dayFolder=getOrCreateFolder_(day,monthFolder),inspectionFolder=getOrCreateFolder_(safe_(data.id)+'_'+zone+'_'+point,dayFolder),jsonName=safe_(data.id)+'.json',existing=inspectionFolder.getFilesByName(jsonName);if(!existing.hasNext()){const metadata=Object.assign({},data),photos=Array.isArray(metadata.fotos)?metadata.fotos:[];metadata.fotos=photos.map((_,i)=>({archivo:safe_(data.id)+'_foto_'+(i+1)+'.jpg'}));metadata.sincronizadoEn=new Date().toISOString();metadata.fotosAlmacenamiento='Google Drive';inspectionFolder.createFile(jsonName,JSON.stringify(metadata,null,2),MimeType.PLAIN_TEXT);photos.forEach((src,i)=>{if(!src||typeof src!=='string')return;const match=src.match(/^data:image\/[^;]+;base64,(.+)$/);if(!match)return;inspectionFolder.createFile(Utilities.newBlob(Utilities.base64Decode(match[1]),'image/jpeg',safe_(data.id)+'_foto_'+(i+1)+'.jpg'));});}return json_({ok:true,id:data.id,folder:inspectionFolder.getUrl()})}
function syncReport_(data){const year=safe_(data.anio||new Date().getFullYear()),month=safe_(data.mes||'SIN_MES'),base=safe_(data.nombre||('Reporte_'+year+'_'+month)),html=buildReportHtml_(year,month);if(!html||html.indexOf('No hay inspecciones')>=0)throw new Error('No hay inspecciones sincronizadas en Drive para ese mes.');const root=getOrCreateFolder_(ROOT_FOLDER_NAME),reports=getOrCreateFolder_('REPORTES_MENSUALES',root),yearFolder=getOrCreateFolder_(year,reports),monthFolder=getOrCreateFolder_(month,yearFolder);['.pdf','.html'].forEach(ext=>{const old=monthFolder.getFilesByName(base+ext);while(old.hasNext())old.next().setTrashed(true)});monthFolder.createFile(base+'.html',html,MimeType.HTML);const pdfFile=monthFolder.createFile(Utilities.newBlob(html,'text/html',base+'.html').getAs(MimeType.PDF).setName(base+'.pdf'));return json_({ok:true,id:base+'.pdf',url:pdfFile.getUrl(),html:base+'.html'})}

function buildReportHtml_(year,month){
  const rows=collectMonthInspections_(year,month);if(!rows.length)return '<!doctype html><html lang="es"><body><h2>No hay inspecciones sincronizadas en Drive para '+escapeHtml_(month)+' '+escapeHtml_(year)+'.</h2></body></html>';
  rows.sort((a,b)=>(a.zona+a.punto+a.fecha).localeCompare(b.zona+b.punto+b.fecha));
  const zones=unique_(rows.map(x=>x.zona)),points=unique_(rows.map(x=>x.zona+'|'+x.punto)),incidence=rows.filter(x=>x.resultado==='CON INCIDENCIA').length,pending=rows.filter(x=>x.estado==='PENDIENTE').length,noInc=rows.filter(x=>x.resultado==='SIN INCIDENCIA').length,photos=rows.reduce((n,x)=>n+(x.photoData||[]).length,0);
  let h='<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Reporte mensual '+escapeHtml_(month)+' '+escapeHtml_(year)+'</title><style>'+reportCss_()+'</style></head><body>';
  h+='<header><h1>REPORTE MENSUAL DE INSPECCIÓN DE INFRAESTRUCTURA</h1><b>MES: '+escapeHtml_(month)+' &nbsp; AÑO: '+escapeHtml_(year)+'</b><div class="small">Generado: '+escapeHtml_(new Date().toLocaleString('es-PE'))+'</div></header><main>';
  h+='<section class="summary"><div><b>'+rows.length+'</b><span>Inspecciones</span></div><div><b>'+zones.length+'</b><span>Áreas</span></div><div><b>'+points.length+'</b><span>Puntos</span></div><div><b>'+incidence+'</b><span>Incidencias</span></div><div><b>'+pending+'</b><span>Pendientes</span></div><div><b>'+noInc+'</b><span>Sin incidencia</span></div><div><b>'+photos+'</b><span>Fotografías</span></div><div><b>'+rows.length+'</b><span>En Drive</span></div></section>';
  let last='';rows.forEach(x=>{if(x.zona!==last){h+='<h2>ÁREA / ZONA: '+escapeHtml_(x.zona)+'</h2>';last=x.zona}h+='<article class="item"><div class="itemTitle">PUNTO DE INSPECCIÓN: '+escapeHtml_(x.punto)+'</div><div class="data"><b>Fecha:</b> '+escapeHtml_(formatDate_(x.fecha))+' &nbsp; <b>Resultado:</b> '+escapeHtml_(x.resultado||'')+(x.estado?' &nbsp; <b>Estado:</b> '+escapeHtml_(x.estado):'')+'</div><div><b>Observación:</b> '+escapeHtml_(x.observacion||'Sin incidencia')+'</div><div class="photoLabel"><b>Fotografías:</b> '+(x.photoData||[]).length+'</div><div class="photos">'+(x.photoData||[]).map(src=>'<img src="'+src+'">').join('')+'</div></article>'});
  h+='</main></body></html>';return h;
}
function reportCss_(){return 'body{font-family:Arial,sans-serif;color:#17202a;margin:0;font-size:10.5pt}header{text-align:center;padding:18px 22px 14px;border-bottom:2px solid #0b57d0}h1{font-size:18pt;margin:0 0 6px}h2{font-size:13pt;background:#e8eef8;padding:6px 9px;margin:12px 0 7px;break-after:avoid;page-break-after:avoid}.small{font-size:8pt;color:#555}main{padding:0 18px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin:10px 0}.summary div{border:1px solid #c9cdd2;padding:5px;text-align:center}.summary b{display:block;font-size:13pt}.summary span{font-size:7.5pt}.item{border:1px solid #c9cdd2;padding:7px;margin:6px 0;break-inside:avoid;page-break-inside:avoid}.itemTitle{font-weight:bold;margin-bottom:4px;font-size:10.5pt}.data{font-size:9pt;margin-bottom:3px}.photoLabel{margin-top:4px;font-size:9pt}.photos{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:4px}.photos img{width:100%;height:125px;object-fit:contain;border:1px solid #ddd;background:#fff;break-inside:avoid;page-break-inside:avoid}.item:has(.photos:empty){padding-bottom:7px}@media print{body{font-size:10pt}header{padding:12px 18px}h2{margin-top:10px}.item{margin:5px 0;padding:6px}.photos img{height:118px}}@media(max-width:700px){.summary{grid-template-columns:repeat(2,1fr)}.photos{grid-template-columns:repeat(2,1fr)}.photos img{height:150px}}'}
function collectMonthInspections_(year,month){const root=getOrCreateFolder_(ROOT_FOLDER_NAME),yf=root.getFoldersByName(String(year));if(!yf.hasNext())return[];const mf=yf.next().getFoldersByName(String(month));if(!mf.hasNext())return[];const rows=[];collectInspectionFiles_(mf.next(),rows);return rows}
function collectInspectionFiles_(folder,rows){const files=folder.getFiles();while(files.hasNext()){const f=files.next();if(f.getName().toLowerCase().endsWith('.json')){try{const x=JSON.parse(f.getBlob().getDataAsString());x.photoData=[];const parent=f.getParents().hasNext()?f.getParents().next():folder;const photoNames=(x.fotos||[]).map(p=>typeof p==='string'?p:p.archivo).filter(Boolean);photoNames.forEach(name=>{const pf=parent.getFilesByName(name);if(pf.hasNext()){const b=pf.next().getBlob();x.photoData.push('data:'+(b.getContentType()||'image/jpeg')+';base64,'+Utilities.base64Encode(b.getBytes()))}});rows.push(x)}catch(err){}}}const sub=folder.getFolders();while(sub.hasNext())collectInspectionFiles_(sub.next(),rows)}
function fileExistsInFolderTree_(folder,fileName){if(folder.getFilesByName(fileName).hasNext())return true;const sub=folder.getFolders();while(sub.hasNext())if(fileExistsInFolderTree_(sub.next(),fileName))return true;return false}
function unique_(arr){return Array.from(new Set(arr))}function formatDate_(value){try{return new Date(value).toLocaleString('es-PE')}catch(e){return String(value||'')}}function escapeHtml_(value){return String(value==null?'':value).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function getOrCreateFolder_(name,parent){const folder=parent||DriveApp.getRootFolder(),it=folder.getFoldersByName(name);return it.hasNext()?it.next():folder.createFolder(name)}function safe_(value){return String(value).replace(/[\\/:*?"<>|]/g,'_').trim().slice(0,120)||'SIN_NOMBRE'}function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}
