const ROOT_FOLDER_NAME = 'INSPECCIONES_INFRAESTRUCTURA';

function doGet(e) {
  const p = (e && e.parameter) || {};
  if (p.action === 'report') return HtmlService.createHtmlOutput(buildReportHtml_(p.anio || new Date().getFullYear(), p.mes || 'SIN_MES')).setTitle('Reporte mensual de inspección');
  if (p.action === 'generateReport') {
    try {
      const result = syncReport_({anio:p.anio, mes:p.mes, nombre:p.nombre || ('Reporte_' + p.anio + '_' + p.mes)});
      const data = JSON.parse(result.getContent());
      if (p.view === '1') return HtmlService.createHtmlOutput('<!doctype html><html lang="es"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial,sans-serif;padding:28px;max-width:560px;margin:auto;text-align:center}a{display:block;padding:14px;margin:12px 0;background:#0b57d0;color:white;text-decoration:none;border-radius:8px}small{color:#666}</style></head><body><h2>✅ Reporte mensual generado</h2><p>El reporte fue guardado en tu Google Drive de trabajo.</p><a href="'+escapeHtml_(data.url)+'" target="_blank">📄 Abrir PDF</a><a href="'+escapeHtml_(data.htmlUrl)+'" target="_blank">🌐 Abrir HTML</a><small>'+escapeHtml_(data.id)+'</small></body></html>').setTitle('Reporte mensual');
      const prefix = String(p.prefix || '');
      if (prefix) return ContentService.createTextOutput(prefix + '(' + result.getContent() + ')').setMimeType(ContentService.MimeType.JAVASCRIPT);
      return result;
    } catch (err) {
      const obj = {ok:false,error:String(err && err.message ? err.message : err)};
      if (p.view === '1') return HtmlService.createHtmlOutput('<h3>❌ No se pudo generar el reporte</h3><p>'+escapeHtml_(obj.error)+'</p>');
      const prefix = String(p.prefix || '');
      if (prefix) return ContentService.createTextOutput(prefix + '(' + JSON.stringify(obj) + ')').setMimeType(ContentService.MimeType.JAVASCRIPT);
      return json_(obj);
    }
  }
  if (p.action === 'check') {
    const id = String(p.id || ''); const result = {ok:fileExistsInFolderTree_(getOrCreateFolder_(ROOT_FOLDER_NAME), id + '.json'),id:id};
    if (p.prefix) return ContentService.createTextOutput(String(p.prefix) + '(' + JSON.stringify(result) + ')').setMimeType(ContentService.MimeType.JAVASCRIPT);
    return json_(result);
  }
  return json_({ok:true,service:'INSPECCIONES_INFRAESTRUCTURA'});
}
function doPost(e){try{const data=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');if(data.action==='syncInspection')return syncInspection_(data);if(data.action==='syncReport')return syncReport_(data);throw new Error('Acción no válida.');}catch(err){return json_({ok:false,error:String(err&&err.message?err.message:err)})}}
function syncInspection_(data){if(!data.id)throw new Error('Falta el ID de inspección.');const root=getOrCreateFolder_(ROOT_FOLDER_NAME),year=String(data.anio||new Date(data.fecha||Date.now()).getFullYear()),month=safe_(data.mes||'SIN_MES'),day=Utilities.formatDate(new Date(data.fecha||Date.now()),Session.getScriptTimeZone(),'yyyy-MM-dd'),zone=safe_(data.zona||'SIN_ZONA'),point=safe_(data.punto||'SIN_PUNTO'),yearFolder=getOrCreateFolder_(year,root),monthFolder=getOrCreateFolder_(month,yearFolder),dayFolder=getOrCreateFolder_(day,monthFolder),inspectionFolder=getOrCreateFolder_(safe_(data.id)+'_'+zone+'_'+point,dayFolder),jsonName=safe_(data.id)+'.json',existing=inspectionFolder.getFilesByName(jsonName);if(!existing.hasNext()){const metadata=Object.assign({},data),photos=Array.isArray(metadata.fotos)?metadata.fotos:[];metadata.fotos=photos.map((_,i)=>({archivo:safe_(data.id)+'_foto_'+(i+1)+'.jpg'}));metadata.sincronizadoEn=new Date().toISOString();metadata.fotosAlmacenamiento='Google Drive';inspectionFolder.createFile(jsonName,JSON.stringify(metadata,null,2),MimeType.PLAIN_TEXT);photos.forEach((src,i)=>{if(!src||typeof src!=='string')return;const match=src.match(/^data:image\/[^;]+;base64,(.+)$/);if(!match)return;inspectionFolder.createFile(Utilities.newBlob(Utilities.base64Decode(match[1]),'image/jpeg',safe_(data.id)+'_foto_'+(i+1)+'.jpg'));});}return json_({ok:true,id:data.id,folder:inspectionFolder.getUrl()})}
function syncReport_(data){const year=safe_(data.anio||new Date().getFullYear()),month=safe_(data.mes||'SIN_MES'),base=safe_(data.nombre||('Reporte_'+year+'_'+month)),html=buildReportHtml_(year,month);if(!html||html.indexOf('No hay inspecciones')>=0)throw new Error('No hay inspecciones sincronizadas en Drive para ese mes.');const root=getOrCreateFolder_(ROOT_FOLDER_NAME),reports=getOrCreateFolder_('REPORTES_MENSUALES',root),yearFolder=getOrCreateFolder_(year,reports),monthFolder=getOrCreateFolder_(month,yearFolder);['.pdf','.html'].forEach(ext=>{const old=monthFolder.getFilesByName(base+ext);while(old.hasNext())old.next().setTrashed(true)});const htmlFile=monthFolder.createFile(base+'.html',html,MimeType.HTML);const pdfFile=monthFolder.createFile(Utilities.newBlob(html,'text/html',base+'.html').getAs(MimeType.PDF).setName(base+'.pdf'));return json_({ok:true,id:base+'.pdf',url:pdfFile.getUrl(),htmlUrl:htmlFile.getUrl()})}

function buildReportHtml_(year,month){
  const rows=collectMonthInspections_(year,month);if(!rows.length)return '<!doctype html><html lang="es"><body><h2>No hay inspecciones sincronizadas en Drive para '+escapeHtml_(month)+' '+escapeHtml_(year)+'.</h2></body></html>';
  rows.sort((a,b)=>(a.zona+a.punto+a.fecha).localeCompare(b.zona+b.punto+b.fecha));
  const zones=unique_(rows.map(x=>x.zona)),points=unique_(rows.map(x=>x.zona+'|'+x.punto)),incidence=rows.filter(x=>x.resultado==='CON INCIDENCIA').length,pending=rows.filter(x=>x.estado==='PENDIENTE').length,noInc=rows.filter(x=>x.resultado==='SIN INCIDENCIA').length,photos=rows.reduce((n,x)=>n+(x.photoData||[]).length,0);
  let h='<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Reporte mensual '+escapeHtml_(month)+' '+escapeHtml_(year)+'</title><style>'+reportCss_()+'</style></head><body><header><h1>REPORTE MENSUAL DE INSPECCIÓN DE INFRAESTRUCTURA</h1><b>MES: '+escapeHtml_(month)+' &nbsp; AÑO: '+escapeHtml_(year)+'</b><div class="small">Generado: '+escapeHtml_(new Date().toLocaleString('es-PE'))+'</div></header><main><section class="summary"><div><b>'+rows.length+'</b><span>Inspecciones</span></div><div><b>'+zones.length+'</b><span>Áreas</span></div><div><b>'+points.length+'</b><span>Puntos</span></div><div><b>'+incidence+'</b><span>Incidencias</span></div><div><b>'+pending+'</b><span>Pendientes</span></div><div><b>'+noInc+'</b><span>Sin incidencia</span></div><div><b>'+photos+'</b><span>Fotografías</span></div><div><b>'+rows.length+'</b><span>En Drive</span></div></section>';
  let last='';rows.forEach(x=>{if(x.zona!==last){h+='<h2>ÁREA / ZONA: '+escapeHtml_(x.zona)+'</h2>';last=x.zona}const arr=x.photoData||[];h+='<article class="item"><div class="itemInfo"><div class="itemTitle">PUNTO DE INSPECCIÓN: '+escapeHtml_(x.punto)+'</div><div class="data"><b>Fecha:</b> '+escapeHtml_(formatDate_(x.fecha))+'</div><div class="data"><b>Resultado:</b> '+escapeHtml_(x.resultado||'')+'</div>'+(x.estado?'<div class="data"><b>Estado:</b> '+escapeHtml_(x.estado)+'</div>':'')+'<div class="data"><b>Observación:</b> '+escapeHtml_(x.observacion||'Sin incidencia')+'</div><div class="photoLabel"><b>Fotografías:</b> '+arr.length+'</div></div><div class="photoArea">'+photoRowsHtml_(arr)+'</div></article>'});
  return h+'</main></body></html>';
}
function photoRowsHtml_(arr){let out='';for(let i=0;i<arr.length;i+=2){out+='<div class="photoRow">';out+='<div class="photoCell">'+(arr[i]?'<img src="'+arr[i]+'">':'')+'</div>';out+='<div class="photoCell">'+(arr[i+1]?'<img src="'+arr[i+1]+'">':'')+'</div>';out+='</div>'}return out}
function reportCss_(){return '@page{size:A4;margin:10mm 9mm 11mm}html,body{font-family:Arial,sans-serif;color:#17202a;margin:0;padding:0;font-size:9pt}header{text-align:center;padding:10px 14px 9px;border-bottom:2px solid #0b57d0}h1{font-size:16pt;margin:0 0 5px}h2{font-size:12pt;background:#e8eef8;padding:5px 8px;margin:9px 0 6px;break-after:avoid;page-break-after:avoid}.small{font-size:7.5pt;color:#555}main{padding:0 2px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;margin:7px 0}.summary div{border:1px solid #c9cdd2;padding:4px;text-align:center}.summary b{display:block;font-size:11pt}.summary span{font-size:7pt}.item{display:grid;grid-template-columns:5.7cm 1fr;column-gap:5mm;border:1px solid #c9cdd2;padding:5px;margin:5px 0;break-inside:auto;page-break-inside:auto;position:relative}.itemInfo{padding:1px 2px}.itemTitle{font-weight:bold;margin-bottom:4px;font-size:9.5pt}.data{font-size:8pt;margin-bottom:2px;line-height:1.25}.photoLabel{margin-top:4px;font-size:8pt}.photoArea{min-width:0}.photoRow{display:grid;grid-template-columns:6cm 6cm;column-gap:3mm;margin-bottom:2mm;break-inside:avoid;page-break-inside:avoid}.photoCell{width:6cm;height:4cm;display:flex;align-items:center;justify-content:center;overflow:hidden;border:1px solid #ddd;background:#fff}.photoCell img{width:6cm;height:4cm;object-fit:contain;display:block}.item + .item{margin-top:5px}@media print{header{padding:8px 10px}h2{margin-top:7px}.item{break-inside:auto;page-break-inside:auto}.photoRow{break-inside:avoid;page-break-inside:avoid}.photoCell,.photoCell img{width:6cm;height:4cm}}@media(max-width:700px){.summary{grid-template-columns:repeat(2,1fr)}.item{grid-template-columns:1fr}.photoRow{grid-template-columns:repeat(2,6cm)}}'}
function collectMonthInspections_(year,month){const root=getOrCreateFolder_(ROOT_FOLDER_NAME),yf=root.getFoldersByName(String(year));if(!yf.hasNext())return[];const mf=yf.next().getFoldersByName(String(month));if(!mf.hasNext())return[];const rows=[];collectInspectionFiles_(mf.next(),rows);return rows}
function collectInspectionFiles_(folder,rows){const files=folder.getFiles();while(files.hasNext()){const f=files.next();if(f.getName().toLowerCase().endsWith('.json')){try{const x=JSON.parse(f.getBlob().getDataAsString());x.photoData=[];const parent=f.getParents().hasNext()?f.getParents().next():folder;const photoNames=(x.fotos||[]).map(p=>typeof p==='string'?p:p.archivo).filter(Boolean);photoNames.forEach(name=>{const pf=parent.getFilesByName(name);if(pf.hasNext()){const b=pf.next().getBlob();x.photoData.push('data:'+(b.getContentType()||'image/jpeg')+';base64,'+Utilities.base64Encode(b.getBytes()))}});rows.push(x)}catch(err){}}}const sub=folder.getFolders();while(sub.hasNext())collectInspectionFiles_(sub.next(),rows)}
function fileExistsInFolderTree_(folder,fileName){if(folder.getFilesByName(fileName).hasNext())return true;const sub=folder.getFolders();while(sub.hasNext())if(fileExistsInFolderTree_(sub.next(),fileName))return true;return false}
function unique_(arr){return Array.from(new Set(arr))}function formatDate_(value){try{return new Date(value).toLocaleString('es-PE')}catch(e){return String(value||'')}}function escapeHtml_(value){return String(value==null?'':value).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function getOrCreateFolder_(name,parent){const folder=parent||DriveApp.getRootFolder(),it=folder.getFoldersByName(name);return it.hasNext()?it.next():folder.createFolder(name)}function safe_(value){return String(value).replace(/[\\/:*?"<>|]/g,'_').trim().slice(0,120)||'SIN_NOMBRE'}function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}